"""Unit tests for meeting notes formatter."""

import pytest
from unittest.mock import patch
from datetime import datetime
from pathlib import Path

from src.notes.formatter import format_meeting_notes, save_notes
from src.notes.summarizer import MeetingSummary


# ── Fixtures ──────────────────────────────────────────────────────────────────

FIXED_DATETIME = datetime(2026, 6, 11, 14, 30, 0)


@pytest.fixture
def freeze_datetime():
    """Freeze datetime.now() so output has predictable dates/times."""
    with patch("src.notes.formatter.datetime") as mock_dt:
        mock_dt.now.return_value = FIXED_DATETIME
        yield mock_dt


@pytest.fixture
def full_summary():
    """A MeetingSummary with every field populated."""
    return MeetingSummary(
        title="Weekly Standup",
        date="2026-06-11",
        duration_minutes=30,
        participants=["Alice", "Bob", "Charlie"],
        key_topics=["Project Alpha progress", "Bug triage", "Sprint planning"],
        decisions=["Prioritize bug #42", "Extend sprint by 2 days"],
        action_items=[
            {"assignee": "Alice", "task": "Fix bug #42", "deadline": "2026-06-12"},
            {"assignee": "Bob", "task": "Update docs", "deadline": "—"},
            {"assignee": "Charlie", "task": "Review PR #17", "deadline": "2026-06-13"},
        ],
        full_transcript="Alice: Good morning everyone.\nBob: Let's discuss the sprint backlog.\nCharlie: I'll take the API refactor.",
        summary="The team discussed progress on Project Alpha, triaged incoming bugs, and finalized the sprint scope.",
    )


@pytest.fixture
def empty_summary():
    """A MeetingSummary where every sequence field is empty and transcript is ''."""
    return MeetingSummary(
        title="Empty Meeting",
        date="2026-06-11",
        duration_minutes=0,
        participants=[],
        key_topics=[],
        decisions=[],
        action_items=[],
        full_transcript="",
        summary="",
    )


@pytest.fixture
def summary_no_transcript():
    """MeetingSummary with summary content but no transcript."""
    return MeetingSummary(
        title="Summary Only",
        date="2026-06-11",
        duration_minutes=15,
        participants=["Dave"],
        key_topics=["Topic A"],
        decisions=["Decision 1"],
        action_items=[{"assignee": "Dave", "task": "Do X", "deadline": "2026-06-15"}],
        full_transcript="",
        summary="Short summary of the discussion.",
    )


@pytest.fixture
def transcript_only_summary():
    """MeetingSummary with a transcript but minimal summary/content."""
    return MeetingSummary(
        title="Transcript Heavy",
        date="2026-06-11",
        duration_minutes=60,
        participants=["Eve"],
        key_topics=[],
        decisions=[],
        action_items=[],
        full_transcript="Eve: This is a very long meeting with lots of discussion.\nEve: We covered many topics.",
        summary="",
    )


# ── format_meeting_notes tests ────────────────────────────────────────────────


class TestFormatMeetingNotes:
    """Tests for format_meeting_notes() — markdown generation."""

    def test_full_summary_includes_all_sections(self, full_summary, freeze_datetime):
        result = format_meeting_notes(full_summary)

        # Header
        assert result.startswith("# Weekly Standup")
        assert "**Date:** 2026-06-11" in result
        assert "**Time:** 14:30" in result
        assert "**Duration:** 30 min" in result

        # Executive Summary
        assert "## Executive Summary" in result
        assert "The team discussed progress on Project Alpha" in result

        # Key Topics
        assert "## Key Topics Discussed" in result
        assert "- Project Alpha progress" in result
        assert "- Bug triage" in result
        assert "- Sprint planning" in result

        # Decisions
        assert "## Decisions Made" in result
        assert "- Prioritize bug #42" in result
        assert "- Extend sprint by 2 days" in result

        # Action Items table
        assert "## Action Items" in result
        assert "| Assignee | Task | Deadline |" in result
        assert "|----------|------|----------|" in result
        assert "| Alice | Fix bug #42 | 2026-06-12 |" in result
        assert "| Bob | Update docs | — |" in result
        assert "| Charlie | Review PR #17 | 2026-06-13 |" in result

        # Full Transcript (present because full_transcript is non-empty)
        assert "## Full Transcript" in result
        assert "Alice: Good morning everyone." in result
        assert "Bob: Let's discuss the sprint backlog." in result

        # Footer
        assert result.endswith("*Generated by Meeting Agent Bot*\n")

    def test_empty_summary_omits_transcript_section(self, empty_summary, freeze_datetime):
        result = format_meeting_notes(empty_summary)

        assert result.startswith("# Empty Meeting")
        assert "**Duration:** 0 min" in result
        assert "## Executive Summary" in result
        assert "## Key Topics Discussed" in result
        assert "## Decisions Made" in result
        assert "## Action Items" in result

        # Transcript section must NOT appear when full_transcript is empty/falsy
        assert "## Full Transcript" not in result

        # Table should still have header and separator, but no data rows
        pipe_lines = [line for line in result.split("\n") if line.startswith("|")]
        assert len(pipe_lines) == 2
        assert pipe_lines[0] == "| Assignee | Task | Deadline |"
        assert pipe_lines[1] == "|----------|------|----------|"

        assert result.endswith("*Generated by Meeting Agent Bot*\n")

    def test_summary_no_transcript_excludes_transcript(self, summary_no_transcript, freeze_datetime):
        result = format_meeting_notes(summary_no_transcript)

        assert "# Summary Only" in result
        assert "Short summary of the discussion." in result
        assert "## Full Transcript" not in result

        # Action items still present
        assert "| Dave | Do X | 2026-06-15 |" in result

    def test_transcript_only_includes_transcript_section(self, transcript_only_summary, freeze_datetime):
        result = format_meeting_notes(transcript_only_summary)

        assert "# Transcript Heavy" in result
        assert "**Duration:** 60 min" in result

        # Transcript section appears
        assert "## Full Transcript" in result
        assert "Eve: This is a very long meeting" in result

        # Summary section still present (even though summary text is empty)
        assert "## Executive Summary" in result

        # No key topics or decisions content (lists are empty)
        assert "## Key Topics Discussed" in result
        assert "## Decisions Made" in result

        # No data rows in action items table
        pipe_lines = [line for line in result.split("\n") if line.startswith("|")]
        assert len(pipe_lines) == 2  # header + separator only

    def test_markdown_separators_present(self, full_summary, freeze_datetime):
        result = format_meeting_notes(full_summary)
        # At least 2 horizontal rules (between sections, plus optional one before transcript)
        assert result.count("---") >= 2

    def test_action_items_missing_keys_get_defaults(self, freeze_datetime):
        """Action items with missing 'assignee' or 'deadline' keys get defaults."""
        summary = MeetingSummary(
            title="Incomplete Items",
            date="2026-06-11",
            duration_minutes=5,
            participants=[],
            key_topics=[],
            decisions=[],
            action_items=[
                {"task": "Only has task"},
                {"assignee": "Alice", "task": "Missing deadline"},
            ],
            full_transcript="",
            summary="",
        )
        result = format_meeting_notes(summary)

        # First item: missing assignee → "Unassigned", missing deadline → "—"
        assert "| Unassigned | Only has task | — |" in result
        # Second item: has assignee, missing deadline → "—"
        assert "| Alice | Missing deadline | — |" in result

    def test_full_transcript_none_treated_as_falsy(self, freeze_datetime):
        """None full_transcript should not produce a transcript section."""
        summary = MeetingSummary(
            title="No Transcript",
            date="2026-06-11",
            duration_minutes=10,
            participants=[],
            key_topics=[],
            decisions=[],
            action_items=[],
            full_transcript=None,  # type: ignore
            summary="Just a summary.",
        )
        result = format_meeting_notes(summary)
        assert "## Full Transcript" not in result
        assert "Just a summary." in result


# ── save_notes tests ──────────────────────────────────────────────────────────


class TestSaveNotes:
    """Tests for save_notes() — file I/O with tmp_path."""

    def test_saves_to_correct_path(self, full_summary, freeze_datetime, tmp_path):
        with patch("src.notes.formatter.settings") as mock_settings:
            mock_settings.notes_dir = tmp_path

            result_path = save_notes(full_summary)

            expected = tmp_path / "2026-06-11_1430_Weekly_Standup.md"
            assert result_path == expected
            assert result_path.exists()

    def test_file_content_matches_format_meeting_notes(self, full_summary, freeze_datetime, tmp_path):
        with patch("src.notes.formatter.settings") as mock_settings:
            mock_settings.notes_dir = tmp_path

            result_path = save_notes(full_summary)

            content = result_path.read_text()
            assert content == format_meeting_notes(full_summary)

    def test_file_content_contains_expected_sections(self, full_summary, freeze_datetime, tmp_path):
        with patch("src.notes.formatter.settings") as mock_settings:
            mock_settings.notes_dir = tmp_path

            result_path = save_notes(full_summary)
            content = result_path.read_text()

            assert "# Weekly Standup" in content
            assert "## Executive Summary" in content
            assert "## Key Topics Discussed" in content
            assert "## Decisions Made" in content
            assert "## Action Items" in content
            assert "## Full Transcript" in content
            assert "*Generated by Meeting Agent Bot*" in content

    def test_filename_truncates_long_titles(self, freeze_datetime, tmp_path):
        """Titles longer than 50 chars are truncated after replacing spaces."""
        long_summary = MeetingSummary(
            title="A Very Long Meeting Title That Exceeds Fifty Characters In Length Definitely",
            date="2026-06-11",
            duration_minutes=10,
            participants=[],
            key_topics=[],
            decisions=[],
            action_items=[],
            full_transcript="",
            summary="",
        )
        with patch("src.notes.formatter.settings") as mock_settings:
            mock_settings.notes_dir = tmp_path

            result_path = save_notes(long_summary)

            # "A Very Long..." → spaces replaced with underscores, truncated to 50
            expected_title_part = "A_Very_Long_Meeting_Title_That_Exceeds_Fifty_Chara"
            assert len(expected_title_part) == 50
            assert expected_title_part in result_path.name

    def test_filename_spaces_replaced_with_underscores(self, freeze_datetime, tmp_path):
        summary = MeetingSummary(
            title="Team Sync",
            date="2026-06-11",
            duration_minutes=5,
            participants=[],
            key_topics=[],
            decisions=[],
            action_items=[],
            full_transcript="",
            summary="",
        )
        with patch("src.notes.formatter.settings") as mock_settings:
            mock_settings.notes_dir = tmp_path

            result_path = save_notes(summary)

            assert " " not in result_path.name
            assert "Team_Sync" in result_path.name

    def test_returns_path_object(self, full_summary, freeze_datetime, tmp_path):
        with patch("src.notes.formatter.settings") as mock_settings:
            mock_settings.notes_dir = tmp_path

            result_path = save_notes(full_summary)

            assert isinstance(result_path, Path)

    def test_empty_summary_writes_without_error(self, empty_summary, freeze_datetime, tmp_path):
        with patch("src.notes.formatter.settings") as mock_settings:
            mock_settings.notes_dir = tmp_path

            result_path = save_notes(empty_summary)

            assert result_path.exists()
            content = result_path.read_text()
            assert "# Empty Meeting" in content
            assert "## Full Transcript" not in content


class TestSanitizeFilename:
    """Tests for _sanitize_filename path traversal and unsafe char handling."""

    def test_normal_title(self):
        from src.notes.formatter import _sanitize_filename
        assert _sanitize_filename("Weekly Standup") == "Weekly_Standup"

    def test_path_traversal(self):
        from src.notes.formatter import _sanitize_filename
        assert ".." not in _sanitize_filename("../../etc/passwd")

    def test_slashes_replaced(self):
        from src.notes.formatter import _sanitize_filename
        result = _sanitize_filename("Standup/Review")
        assert "/" not in result
        assert "\\" not in result

    def test_colons_replaced(self):
        from src.notes.formatter import _sanitize_filename
        result = _sanitize_filename("Meeting: Q3 Review")
        assert ":" not in result

    def test_truncation(self):
        from src.notes.formatter import _sanitize_filename
        long = "A" * 100
        assert len(_sanitize_filename(long)) <= 50

    def test_special_chars_replaced(self):
        from src.notes.formatter import _sanitize_filename
        result = _sanitize_filename('Meeting*With?"Bad<>Chars|')
        for ch in r'\:*?"<>|/':
            assert ch not in result

    def test_empty_string(self):
        from src.notes.formatter import _sanitize_filename
        # Should not crash on empty input
        result = _sanitize_filename("")
        assert isinstance(result, str)
