"""Format MeetingSummary as Markdown and save to disk."""
from datetime import datetime
from pathlib import Path

from src.config import settings
from src.notes.summarizer import MeetingSummary


def format_meeting_notes(summary: MeetingSummary) -> str:
    now = datetime.now()
    lines = [
        f"# {summary.title}",
        "",
        f"**Date:** {summary.date} | **Time:** {now.strftime('%H:%M')} | **Duration:** {summary.duration_minutes} min",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        summary.summary,
        "",
        "## Key Topics Discussed",
        "",
    ]

    for topic in summary.key_topics:
        lines.append(f"- {topic}")
    lines.append("")

    lines.extend([
        "## Decisions Made",
        "",
    ])
    for decision in summary.decisions:
        lines.append(f"- {decision}")
    lines.append("")

    lines.extend([
        "---",
        "",
        "## Action Items",
        "",
        "| Assignee | Task | Deadline |",
        "|----------|------|----------|",
    ])
    for item in summary.action_items:
        assignee = item.get("assignee", "Unassigned")
        task = item.get("task", "")
        deadline = item.get("deadline", "—")
        lines.append(f"| {assignee} | {task} | {deadline} |")
    lines.append("")

    if summary.full_transcript:
        lines.extend([
            "---",
            "",
            "## Full Transcript",
            "",
            summary.full_transcript,
            "",
        ])

    lines.append("*Generated by Meeting Agent Bot*")
    lines.append("")

    return "\n".join(lines)


def sanitize_filename(title: str) -> str:
    """Sanitize a title for use as a filename: remove path traversal and unsafe chars."""
    import re
    # Replace path separators and other unsafe filesystem characters
    safe = re.sub(r'[/\\:*?"<>|]', '_', title)
    # Remove any directory traversal attempts
    safe = safe.replace('..', '')
    # Collapse multiple underscores/spaces
    safe = re.sub(r'[_\s]+', '_', safe).strip('_')
    return safe[:50]


def save_notes(summary: MeetingSummary) -> Path:
    now = datetime.now()
    safe_title = sanitize_filename(summary.title)
    filename = f"{now.strftime('%Y-%m-%d_%H%M')}_{safe_title}.md"

    settings.notes_dir.mkdir(parents=True, exist_ok=True)
    path = settings.notes_dir / filename
    path.write_text(format_meeting_notes(summary))
    return path
